<?php

/**
 * This is the model base class for the table "secciones_grados".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "SeccionesGrados".
 *
 * Columns in table "secciones_grados" available as properties of the model,
 * followed by relations of table "secciones_grados" available as properties of the model.
 *
 * @property integer $seccion_id
 * @property integer $grado_id
 * @property integer $id
 * @property integer $estado
 * @property integer $alum_max_grado
 *
 * @property ProcesosPeriodos[] $procesosPeriodoses
 * @property Grados $grado
 * @property Secciones $seccion
 */
abstract class BaseSeccionesGrados extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'secciones_grados';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Seccion Asociada a un Grado |Secciones Asociadas a los Grados', $n);
	}

	public static function representingColumn() {
		
		//return 'seccion_id,grado_id';
		return null;
	}
	
	public function __toString() {
		$nombre_seccion= $this->seccion;
		$nombre_grado = $this->grado;
		
		$resultado= $nombre_seccion." - ".$nombre_grado; 
		return $resultado;
	}
	
	public function rules() {
		return array(
			array('seccion_id, grado_id, alum_max_grado', 'required'),
			array('seccion_id, grado_id, estado, alum_max_grado', 'numerical', 'integerOnly'=>true),
			array('estado', 'default', 'setOnEmpty' => true, 'value' => null),
			array('seccion_id, grado_id, id, estado, alum_max_grado', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			// 'procesosPeriodoses' => array(self::HAS_MANY, 'ProcesosPeriodos', 'seccion_grado_id'),
			'grado' => array(self::BELONGS_TO, 'Grados', 'grado_id'),
			'seccion' => array(self::BELONGS_TO, 'Secciones', 'seccion_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'seccion_id' => null,
			'grado_id' => null,
			'id' => Yii::t('app', 'ID'),
			'estado' => Yii::t('app', 'Estado'),
			'alum_max_grado' => Yii::t('app', 'Número maximo de alumnos por grado'),
			//'procesosPeriodoses' => null,
			'grado' => null,
			'seccion' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('seccion_id', $this->seccion_id);
		$criteria->compare('grado_id', $this->grado_id);
		$criteria->compare('id', $this->id);
		$criteria->compare('estado', 1);
		$criteria->compare('alum_max_grado', $this->alum_max_grado);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}