<?php

/**
 * This is the model base class for the table "Provincia".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Provincia".
 *
 * Columns in table "Provincia" available as properties of the model,
 * followed by relations of table "Provincia" available as properties of the model.
 *
 * @property integer $id
 * @property string $nombre
 * @property integer $provincia_region_id
 * @property integer $estado
 *
 * @property Comuna[] $comunas
 * @property Region $provinciaRegion
 */
abstract class BaseProvincia extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'Provincia';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Provincia|Provincias', $n);
	}

	public static function representingColumn() {
		return 'nombre';
	}

	public function rules() {
		return array(
			array('id, nombre, provincia_region_id', 'required'),
			array('id, provincia_region_id, estado', 'numerical', 'integerOnly'=>true),
			array('nombre', 'length', 'max'=>23),
			array('estado', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, nombre, provincia_region_id, estado', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'comunas' => array(self::HAS_MANY, 'Comuna', 'comuna_provincia_id'),
			'provinciaRegion' => array(self::BELONGS_TO, 'Region', 'provincia_region_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'nombre' => Yii::t('app', 'Nombre'),
			'provincia_region_id' => null,
			'estado' => Yii::t('app', 'Estado'),
			'comunas' => null,
			'provinciaRegion' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('nombre', $this->nombre, true);
		$criteria->compare('provincia_region_id', $this->provincia_region_id);
		$criteria->compare('estado', $this->estado);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}