<?php

/**
 * This is the model base class for the table "tasas_interes".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "TasasInteres".
 *
 * Columns in table "tasas_interes" available as properties of the model,
 * followed by relations of table "tasas_interes" available as properties of the model.
 *
 * @property integer $id
 * @property string $nombre
 * @property double $porcentaje
 * @property integer $estado
 *
 * @property Compromisos[] $compromisoses
 * @property Pagos[] $pagoses
 */
abstract class BaseTasasInteres extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tasas_interes';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Tasa de Interes |Tasas de Interes', $n);
	}

	public static function representingColumn() {
		return 'nombre';
	}

	public function rules() {
		return array(
			array('nombre, porcentaje', 'required'),
			array('estado', 'numerical', 'integerOnly'=>true),
			array('porcentaje', 'numerical'),
			array('nombre', 'length', 'max'=>200),
			array('estado', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, nombre, porcentaje, estado', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'compromisoses' => array(self::HAS_MANY, 'Compromisos', 'tasa_interes_id','condition' => 'compromisoses.estado = 1'),
			'pagoses' => array(self::HAS_MANY, 'Pagos', 'tasa_interes_id','condition' => 'pagoses.estado = 1'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'nombre' => Yii::t('app', 'Nombre'),
			'porcentaje' => Yii::t('app', 'Porcentaje'),
			'estado' => Yii::t('app', 'Estado'),
			'compromisoses' => null,
			'pagoses' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('nombre', $this->nombre, true);
		$criteria->compare('porcentaje', $this->porcentaje);
		$criteria->compare('estado', 1);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}