<?php

/**
 * This is the model base class for the table "pagos".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Pagos".
 *
 * Columns in table "pagos" available as properties of the model,
 * followed by relations of table "pagos" available as properties of the model.
 *
 * @property integer $id
 * @property integer $compromiso_detalle_id
 * @property integer $tipo_pago_id
 * @property string $cheque_numero
 * @property integer $cheque_rut
 * @property string $cheque_plaza
 * @property integer $cheque_banco_id
 * @property string $observaciones
 * @property integer $tasa_interes_id
 * @property integer $interes_cobrado
 * @property string $fecha_pago 
 * @property string $cheque_fecha
 * @property integer $valor_cuota
 * @property integer $pago_total
 * @property string $cheque_serie
 * @property string $cheque_rut_serie
 * @property integer $estado
 * 
 * @property Bancos $chequeBanco
 * @property DetallesCompromisos $compromisoDetalle
 * @property TiposPagos $tipoPago
 * @property TasasInteres $tasaInteres
 */
abstract class BasePagos extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'pagos';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Pago|Pagos', $n);
	}

	public static function representingColumn() {
		return 'fecha_pago';
	}

	public function rules() {
        return array(
            array('compromiso_detalle_id, tipo_pago_id', 'required'),
            array('compromiso_detalle_id, tipo_pago_id, cheque_rut, cheque_banco_id, pago_total, descuento, estado', 'numerical', 'integerOnly'=>true),
            array('cheque_numero', 'length', 'max'=>50),
            array('cheque_plaza', 'length', 'max'=>100),
            array('cheque_serie, cheque_rut_serie', 'length', 'max'=>20),
            array('observaciones', 'safe'),
            array('compromiso_detalle_id', 'unique','message'=>'El compromiso debe ser unico.'),
            array('cheque_numero, cheque_rut, cheque_plaza, cheque_banco_id, observaciones, pago_total, cheque_serie, cheque_rut_serie, descuento, estado', 'default', 'setOnEmpty' => true, 'value' => null),
            array('id, compromiso_detalle_id, tipo_pago_id, cheque_numero, cheque_rut, cheque_plaza, cheque_banco_id, observaciones, fecha_pago, cheque_fecha, pago_total, cheque_serie, cheque_rut_serie, descuento, estado', 'safe', 'on'=>'search'),
        );
	}

	public function relations() {
		return array(			
			'chequeBanco' => array(self::BELONGS_TO, 'Bancos', 'cheque_banco_id','condition' => 'chequeBanco.estado = 1'),
			'compromisoDetalle' => array(self::BELONGS_TO, 'DetallesCompromisos', 'compromiso_detalle_id','condition' => 'compromisoDetalle.estado = 1'),
			'tipoPago' => array(self::BELONGS_TO, 'TiposPagos', 'tipo_pago_id','condition' => 'tipoPago.estado = 1'),			
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
            'compromiso_detalle_id' => null,
            'tipo_pago_id' => null,
            'cheque_numero' => Yii::t('app', 'Cheque Numero'),
            'cheque_rut' => Yii::t('app', 'Cheque Rut'),
            'cheque_plaza' => Yii::t('app', 'Cheque Plaza'),
            'cheque_banco_id' => null,
            'observaciones' => Yii::t('app', 'Observaciones'),
            'fecha_pago' => Yii::t('app', 'Fecha Pago'),
            'cheque_fecha' => Yii::t('app', 'Cheque Fecha'),
            'pago_total' => Yii::t('app', 'Pago total'),            
            'cheque_serie' => Yii::t('app', 'Cheque Serie'),
            'cheque_rut_serie' => Yii::t('app', 'Cheque Rut Serie'),
            'descuento' => Yii::t('app', 'Descuento'),
            'estado' => Yii::t('app', 'Estado'),
            'chequeBanco' => null,
            'compromisoDetalle' => null,
            'tipoPago' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
        $criteria->compare('compromiso_detalle_id', $this->compromiso_detalle_id);
        $criteria->compare('tipo_pago_id', $this->tipo_pago_id);
        $criteria->compare('cheque_numero', $this->cheque_numero, true);
        $criteria->compare('cheque_rut', $this->cheque_rut);
        $criteria->compare('cheque_plaza', $this->cheque_plaza, true);
        $criteria->compare('cheque_banco_id', $this->cheque_banco_id);
        $criteria->compare('observaciones', $this->observaciones, true);
        $criteria->compare('fecha_pago', $this->fecha_pago, true);
        $criteria->compare('cheque_fecha', $this->cheque_fecha, true);
        $criteria->compare('pago_total', $this->pago_total);        
        $criteria->compare('cheque_serie', $this->cheque_serie, true);
        $criteria->compare('cheque_rut_serie', $this->cheque_rut_serie, true);
        $criteria->compare('descuento', $this->descuento); 
		$criteria->compare('estado', 1);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}