<?php

/**
 * This is the model base class for the table "comuna".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Comuna".
 *
 * Columns in table "comuna" available as properties of the model,
 * followed by relations of table "comuna" available as properties of the model.
 *
 * @property integer $id
 * @property string $nombre
 * @property integer $estado
 *
 * @property Alumnos[] $alumnoses
 * @property Encargados[] $encargadoses
 */
abstract class BaseComuna extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'comuna';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Comuna|Comunas', $n);
	}

	public static function representingColumn() {
		return 'nombre';
	}

	public function rules() {
		return array(
			array('id, nombre', 'required'),
			array('id, estado', 'numerical', 'integerOnly'=>true),
			array('nombre', 'length', 'max'=>20),
			array('estado', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, nombre, estado', 'safe', 'on'=>'search'),
			array('id','unique','message'=>'{attribute} : {value}  se encuentra registrado en la base de datos !!!'),
		);
	}

	public function relations() {
		return array(
			'alumnoses' => array(self::HAS_MANY, 'Alumnos', 'comuna_id','condition' => 'alumnoses.estado = 1'),
			'encargadoses' => array(self::HAS_MANY, 'Encargados', 'comuna_id','condition' => 'encargadoses.estado = 1'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'nombre' => Yii::t('app', 'Nombre'),
			'estado' => Yii::t('app', 'Estado'),
			'alumnoses' => null,
			'encargadoses' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('nombre', $this->nombre, true);
		$criteria->compare('estado', 1);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}