<?php

/**
 * This is the model base class for the table "procesos_periodos".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ProcesosPeriodos".
 *
 * Columns in table "procesos_periodos" available as properties of the model,
 * followed by relations of table "procesos_periodos" available as properties of the model.
 *
 * @property integer $alumno_rut
 * @property integer $periodo_id
 * @property integer $seccion_grado_id
 * @property integer $estado
 * @property integer $pago_pendiente
 * @property integer $promovido
 *
 * @property Compromisos[] $compromisoses
 * @property Alumnos $alumnoRut
 * @property Periodos $periodo
 * @property SeccionesGrados $seccionGrado
 */
abstract class BaseProcesosPeriodos extends GxActiveRecord {
	public $nombreCurso,$nombreCompleto;
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'procesos_periodos';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Matricula|Matriculas', $n);
	}

	public static function representingColumn() {
		return 'alumno_rut';
	}

	public function rules() {
		return array(
			array('alumno_rut, periodo_id, seccion_grado_id', 'required'),
			array('alumno_rut, periodo_id, seccion_grado_id, estado, pago_pendiente, promovido', 'numerical', 'integerOnly'=>true),
			array('estado, pago_pendiente, promovido', 'default', 'setOnEmpty' => true, 'value' => null),
			array('alumno_rut, periodo_id, seccion_grado_id, estado, pago_pendiente, promovido', 'safe', 'on'=>'search'),
			array('alumno_rut', 'UniqueAttributesValidator', 'with'=>'periodo_id','message'=>'{attribute} "{value}" Se ecuentra matriculado en esté periodo.'),
        );		
	
	}

	public function relations() {
		return array(
			'compromisoses' => array(self::HAS_MANY, 'Compromisos', 'proceso_periodo_id'),
			'alumnoRut' => array(self::BELONGS_TO, 'Alumnos', 'alumno_rut'),
			'periodo' => array(self::BELONGS_TO, 'Periodos', 'periodo_id'),
			'seccionGrado' => array(self::BELONGS_TO, 'SeccionesGrados', 'seccion_grado_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'alumno_rut' => null,
			'periodo_id' => Yii::t('app', 'Período'),
			'seccion_grado_id' => Yii::t('app', 'Curso '),
			'estado' => Yii::t('app', 'Estado'),
			'pago_pendiente' => Yii::t('app', 'Tiene Pagos Pendientes'),
			'promovido' => Yii::t('app', 'Promovido'),
			'compromisoses' => null,
			'alumnoRut' => null,
			'periodo' => null,
			'seccionGrado' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('alumno_rut', $this->alumno_rut);
		$criteria->compare('periodo_id', Yii::app()->session['idPeriodo']);
		$criteria->compare('seccion_grado_id', $this->seccion_grado_id);
		$criteria->compare('estado', 1);
		$criteria->compare('pago_pendiente', $this->pago_pendiente);
		$criteria->compare('promovido', $this->promovido);
		//$criteria->condition='t.periodo_id='.Yii::app()->session['idPeriodo'];

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
	public function searchCursos() {
			$criteria = new CDbCriteria;
			//$criteria->compare('nombreCurso', $this->nombreCurso);
			//$criteria->compare('seccion_grado_id', $this->seccion_grado_id, true);
			//$criteria->compare('secciones_grados.id', $this->secciones_grados.id);
			//$criteria->compare('alumno_rut', $this->alumno_rut);
			//$criteria->compare('nombreCompleto', $this->nombreCompleto);

			$criteria->join = ' INNER JOIN alumnos ON (t.alumno_rut = alumnos.rut)
								INNER JOIN secciones_grados ON (t.seccion_grado_id = secciones_grados.id)
								INNER JOIN secciones ON ( secciones_grados.seccion_id = secciones.id)
								INNER JOIN grados ON(secciones_grados.grado_id = grados.id)';
			$criteria->distinct =true;
			$criteria->select= "t.seccion_grado_id,t.id,
								secciones_grados.id,
								concat (secciones.nombre,'-',grados.nombre) as nombreCurso,
								t.alumno_rut,
								concat(alumnos.apellido_paterno,' ',alumnos.apellido_materno,' ',alumnos.nombre) as nombreCompleto";
			
			/*$criteria->select= "t.seccion_grado_id,t.id,
								secciones_grados.id,
								t.alumno_rut";
			*/
			$criteria->condition = "t.periodo_id =".Yii::app()->session['idPeriodo']." AND 
									t.estado = 1 AND secciones_grados.estado = 1";
			
			$criteria->addCondition('t.seccion_grado_id = :seccion_grado_id'); // add your sql WHERE condition
			$criteria->params[':seccion_grado_id'] = $this->seccion_grado_id; // bind your parameter
			
			return new CActiveDataProvider(get_class($this), array(
			'criteria' => $criteria,
			'sort'=>array(
                'defaultOrder'=>'alumnos.apellido_paterno ASC,alumnos.apellido_materno ASC,alumnos.nombre ASC',
            ),
            'pagination' => array('pageSize' => 60,)
			));
	}
}