<?php

/**
 * This is the model base class for the table "encargados".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Encargados".
 *
 * Columns in table "encargados" available as properties of the model,
 * followed by relations of table "encargados" available as properties of the model.
 *
 * @property integer $rut
 * @property string $dv
 * @property string $nombre
 * @property string $apellido_paterno
 * @property string $apellido_materno
 * @property string $telefono_laboral
 * @property string $telefono_fijo
 * @property string $celular
 * @property string $direccion_particular
 * @property string $villa_poblacion
 * @property integer $comuna_id
 * @property string $fecha_actualizacion
 * @property integer $responsable_actualizacion
 * @property integer $estado
 * @property integer $parentesco_id
 * @property integer $estudios_superiores_anios
 * @property string $ocupacion
 *
 * @property Alumnos[] $alumnoses
 * @property Alumnos[] $alumnoses1
 * @property Alumnos[] $alumnoses2
 * @property Comuna $comuna
 * @property Parentescos $parentesco
 */
abstract class BaseEncargados extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'encargados';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Encargado  | Encargados', $n);
	}

	public static function representingColumn() {
		return 'rut';
	}

	public function rules() {
		return array(
			array('rut, dv, nombre, apellido_paterno, apellido_materno, responsable_actualizacion, parentesco_id', 'required'),
			array('rut, comuna_id, responsable_actualizacion, estado, parentesco_id, estudios_superiores_anios', 'numerical', 'integerOnly'=>true),
			array('dv', 'length', 'max'=>1),
			array('nombre, apellido_paterno, apellido_materno, ocupacion', 'length', 'max'=>50),
			array('telefono_laboral, telefono_fijo, celular', 'length', 'max'=>12),
			array('direccion_particular, villa_poblacion', 'length', 'max'=>200),
			array('rut, telefono_laboral, telefono_fijo, celular, direccion_particular, villa_poblacion, comuna_id, estado, estudios_superiores_anios, ocupacion', 'default', 'setOnEmpty' => true, 'value' => null),
			array('rut, dv, nombre, apellido_paterno, apellido_materno, telefono_laboral, telefono_fijo, celular, direccion_particular, villa_poblacion, comuna_id, fecha_actualizacion, responsable_actualizacion, estado, parentesco_id, estudios_superiores_anios, ocupacion', 'safe', 'on'=>'search'),
			array('rut','unique','message'=>'{attribute} : {value}  se encuentra registrado en la base de datos !!!'),
			
		 );
	}

	public function relations() {
		return array(
			'alumnoses' => array(self::HAS_MANY, 'Alumnos', 'apoderado_rut'),
			'alumnoses1' => array(self::HAS_MANY, 'Alumnos', 'madre_rut'),
			'alumnoses2' => array(self::HAS_MANY, 'Alumnos', 'padre_rut'),
			'comuna' => array(self::BELONGS_TO, 'Comuna', 'comuna_id'),
			'parentesco' => array(self::BELONGS_TO, 'Parentescos', 'parentesco_id'),
			'responsableActualizacion' => array(self::BELONGS_TO, 'Users', 'responsable_actualizacion'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'rut' => Yii::t('app', 'Rut'),
			'dv' => Yii::t('app', 'Dv'),
			'nombre' => Yii::t('app', 'Nombre'),
			'apellido_paterno' => Yii::t('app', 'Apellido Paterno'),
			'apellido_materno' => Yii::t('app', 'Apellido Materno'),
			'telefono_laboral' => Yii::t('app', 'Teléfono Laboral'),
			'telefono_fijo' => Yii::t('app', 'Teléfono Fijo'),
			'celular' => Yii::t('app', 'Celular'),
			'direccion_particular' => Yii::t('app', 'Dirección Particular'),
			'villa_poblacion' => Yii::t('app', 'Villa Población'),
			'comuna_id' => null,
			'fecha_actualizacion' => Yii::t('app', 'Fecha Actualizacion'),
			'responsable_actualizacion' => Yii::t('app', 'Responsable Actualizacion'),
			'estado' => Yii::t('app', 'Estado'),
			'parentesco_id' => null,
			'estudios_superiores_anios' => Yii::t('app', 'Años de estudios Superiores'),
			'ocupacion' => Yii::t('app', 'Ocupacion'),
			'alumnoses' => null,
			'alumnoses1' => null,
			'alumnoses2' => null,
			'comuna' => null,
			'parentesco' => null,
			'responsableActualizacion' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('rut', $this->rut);
		$criteria->compare('dv', $this->dv, true);
		$criteria->compare('nombre', $this->nombre, true);
		$criteria->compare('apellido_paterno', $this->apellido_paterno, true);
		$criteria->compare('apellido_materno', $this->apellido_materno, true);
		$criteria->compare('telefono_laboral', $this->telefono_laboral, true);
		$criteria->compare('telefono_fijo', $this->telefono_fijo, true);
		$criteria->compare('celular', $this->celular, true);
		$criteria->compare('direccion_particular', $this->direccion_particular, true);
		$criteria->compare('villa_poblacion', $this->villa_poblacion, true);
		$criteria->compare('comuna_id', $this->comuna_id);
		$criteria->compare('fecha_actualizacion', $this->fecha_actualizacion, true);
		$criteria->compare('responsable_actualizacion', $this->responsable_actualizacion);
		$criteria->compare('estado', 1);
		$criteria->compare('parentesco_id', $this->parentesco_id);
		$criteria->compare('estudios_superiores_anios', $this->estudios_superiores_anios);
		$criteria->compare('ocupacion', $this->ocupacion, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}