<?php

/**
 * This is the model base class for the table "compromisos".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Compromisos".
 *
 * Columns in table "compromisos" available as properties of the model,
 * followed by relations of table "compromisos" available as properties of the model.
 *
 * @property integer $id
 * @property string $fecha_actual
 * @property integer $tipo_compromiso_id
 * @property integer $compromiso_id_repactacion
 * @property string $observaciones
 * @property integer $responsable_id
 * @property string $evidencia_pdf
 * @property integer $tasa_interes_id
 * @property integer $numero_cuotas
 * @property integer $monto_sin_interes
 * @property string $fecha_primera_cuota
 * @property integer $monto_total
 * @property integer $medio_pago_id
 * @property integer $proceso_periodo_id
 * @property integer $estado
 *
 * @property ProcesosPeriodos $procesoPeriodo
 * @property Users $responsable
 * @property MediosPagos $medioPago
 * @property TasasInteres $tasaInteres
 * @property TiposCompromisos $tipoCompromiso
 * @property DetallesCompromisos[] $detallesCompromisoses
 */
abstract class BaseCompromisos extends GxActiveRecord {
	
	public $documento;

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'compromisos';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Compromiso|Compromisos', $n);
	}

	public static function representingColumn() {
		return 'proceso_periodo_id';
	}

	public function rules() {
		return array(
			array('documento', 'file', 'types'=>'pdf'),
			array('tasa_interes_id,fecha_actual, tipo_compromiso_id, responsable_id, monto_sin_interes, monto_total, medio_pago_id, proceso_periodo_id,numero_cuotas', 'required'),
			array('tipo_compromiso_id, responsable_id, tasa_interes_id, numero_cuotas, monto_sin_interes, monto_total, medio_pago_id, proceso_periodo_id, estado', 'numerical', 'integerOnly'=>true),
			array('evidencia_pdf', 'length', 'max'=>200),
			array('observaciones, fecha_primera_cuota', 'safe'),
			array('observaciones, evidencia_pdf, tasa_interes_id, numero_cuotas, fecha_primera_cuota, estado', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, fecha_actual, tipo_compromiso_id, observaciones, responsable_id, evidencia_pdf, tasa_interes_id, numero_cuotas, monto_sin_interes, fecha_primera_cuota, monto_total, medio_pago_id, proceso_periodo_id, estado', 'safe', 'on'=>'search'),
			array('proceso_periodo_id','unique','message'=>'{attribute} : {value}  se encuentra registrado en la base de datos !!!'),
		);
	}

	public function relations() {
		return array(
			'procesoPeriodo' => array(self::BELONGS_TO, 'ProcesosPeriodos', 'proceso_periodo_id'),
			//'responsable' => array(self::BELONGS_TO, 'Users', 'responsable_id'),
			'medioPago' => array(self::BELONGS_TO, 'MediosPagos', 'medio_pago_id'),
			'tasaInteres' => array(self::BELONGS_TO, 'TasasInteres', 'tasa_interes_id'),
			'tipoCompromiso' => array(self::BELONGS_TO, 'TiposCompromisos', 'tipo_compromiso_id'),
			'detallesCompromisoses' => array(self::HAS_MANY, 'DetallesCompromisos', 'compromiso_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'fecha_actual' => Yii::t('app', 'Fecha Actual'),
			'tipo_compromiso_id' => null,
			//'compromiso_id_repactacion' => Yii::t('app', 'Compromiso Id Repactacion'),
			'observaciones' => Yii::t('app', 'Observaciones'),
			'responsable_id' => null,
			'evidencia_pdf' => Yii::t('app', 'Evidencia Pdf'),
			'tasa_interes_id' => null,
			'numero_cuotas' => Yii::t('app', 'Numero Cuotas'),
			'monto_sin_interes' => Yii::t('app', 'Monto Sin Interes'),
			'fecha_primera_cuota' => Yii::t('app', 'Fecha Primera Cuota'),
			'monto_total' => Yii::t('app', 'Monto Total'),
			'medio_pago_id' => null,
			'proceso_periodo_id' => null,
			'estado' => Yii::t('app', 'Estado'),
			'procesoPeriodo' => null,
			//'responsable' => null,
			'medioPago' => null,
			'tasaInteres' => null,
			'tipoCompromiso' => null,
			'detallesCompromisoses' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('fecha_actual', $this->fecha_actual, true);
		$criteria->compare('tipo_compromiso_id', $this->tipo_compromiso_id);
		//$criteria->compare('compromiso_id_repactacion', $this->compromiso_id_repactacion);
		$criteria->compare('observaciones', $this->observaciones, true);
		$criteria->compare('responsable_id', $this->responsable_id);
		$criteria->compare('evidencia_pdf', $this->evidencia_pdf, true);
		$criteria->compare('tasa_interes_id', $this->tasa_interes_id);
		$criteria->compare('numero_cuotas', $this->numero_cuotas);
		$criteria->compare('monto_sin_interes', $this->monto_sin_interes);
		$criteria->compare('fecha_primera_cuota', $this->fecha_primera_cuota, true);
		$criteria->compare('monto_total', $this->monto_total);
		$criteria->compare('medio_pago_id', $this->medio_pago_id);
		$criteria->compare('proceso_periodo_id', $this->proceso_periodo_id);
		$criteria->compare('estado', 1);
		if(isset(Yii::app()->session['idPeriodo'])){
			$criteria->join='INNER JOIN procesos_periodos pp on 	t.proceso_periodo_id=pp.id';
			$criteria->distinct =true;
            $criteria->select='t.*';	
            $criteria->condition='t.estado = 1 AND pp.periodo_id = '.Yii::app()->session['idPeriodo'];
		}
		
		
		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}