<?php

/**
 * This is the model base class for the table "periodos".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Periodos".
 *
 * Columns in table "periodos" available as properties of the model,
 * followed by relations of table "periodos" available as properties of the model.
 *
 * @property integer $id
 * @property string $nombre
 * @property integer $estado
 *
 * @property ProcesosPeriodos[] $procesosPeriodoses
 */
abstract class BasePeriodos extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'periodos';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Periodo|Periodos', $n);
	}

	public static function representingColumn() {
		return 'nombre';
	}

	public function rules() {
		return array(
			array('nombre', 'required'),
			array('estado', 'numerical', 'integerOnly'=>true),
			array('nombre', 'length', 'max'=>50),
			array('estado', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, nombre, estado', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			//'procesosPeriodoses' => array(self::HAS_MANY, 'ProcesosPeriodos', 'periodo_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'nombre' => Yii::t('app', 'Nombre'),
			'estado' => Yii::t('app', 'Estado'),
			//'procesosPeriodoses' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('nombre', $this->nombre, true);
		$criteria->compare('estado', 1);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}